version: "3.4"
volumes:
  node_modules:
services:
  frontend:
    image: node:18.15-alpine
    container_name: holocron-web
    entrypoint: /bin/sh
    command: -c "npm i && npm run dev"
    ports:
      - "8000:8000"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
      - node_modules:/srv/app/node_modules
    tty: true
  backend:
    container_name: holocron-rest
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    ports:
      - "8080:8080"

