import {Participant} from "@/state/participantsStore";

export type EffectTarget = {
    type: 'character' | 'initiative' | 'global';
    participantId?: string;
    slot?: number;
};

export type EffectBehavior = {
    type: 'active' | 'passive' | 'reminder';
    trigger: 'immediate' | 'turn-start' | 'turn-action' | 'turn-end' | 'round-start' | 'round-end';
};

export interface ToastConfig {
    title: string;
    description?: string;
    status?: 'info' | 'warning' | 'success' | 'error';
}

export interface Effect {
    id: string;
    name: string;
    description?: string;
    target: EffectTarget;
    behavior: EffectBehavior;
    type?: string;
    duration?: number;
    apply?: (participant?: Participant, durationMessage?: string) => void;

    // Extended fields for common SWRPG statuses (optional for backward compatibility)
    status?: StatusType;
    // Rank (X) for effects like Disoriented X, Ensnared X, Burn X
    rank?: number;
    // Damage over time (e.g., Burn)
    overTimeDamage?: number;
    overTimeType?: 'wounds' | 'strain';
}

export interface ParticipantEffect extends Effect {
    type: string;
    duration: number;
}

export interface ActiveEffect {
    effect: ParticipantEffect;
    target: EffectTarget;
    remainingDuration: number;
    appliedAt: number;
}

// Classification of common SWRPG status effects
export type StatusType =
    | 'staggered'
    | 'prone'
    | 'disoriented'
    | 'immobilized'
    | 'ensnared'
    | 'knocked-down'
    | 'burn';

// Factories to create standardized status effects
// Note: id should be generated by the caller (e.g., nanoid)
export const StatusFactories = {
    staggered: (id: string, target: EffectTarget, duration: number = 1): Effect => ({
        id,
        name: 'Staggered',
        description: 'Cannot perform actions while staggered.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'staggered',
        duration,
    }),

    prone: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Prone',
        description:
            'Treated as prone: stand up with a maneuver; melee/ranged modifiers apply per rules.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'prone',
        // Duration intentionally undefined; remove when the character stands up.
    }),

    disoriented: (id: string, target: EffectTarget, rank: number = 1, duration: number = 1): Effect => ({
        id,
        name: `Disoriented ${rank}`,
        description: `Suffers ${rank} Setback on all checks while disoriented.`,
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'disoriented',
        rank,
        duration,
    }),

    immobilized: (id: string, target: EffectTarget, duration: number = 1): Effect => ({
        id,
        name: 'Immobilized',
        description: 'Cannot perform maneuvers.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'immobilized',
        duration,
    }),

    ensnared: (id: string, target: EffectTarget, rank: number = 1, duration?: number): Effect => ({
        id,
        name: `Ensnared ${rank}`,
        description:
            'Cannot perform maneuvers for X rounds (may attempt to break free per rules).',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'ensnared',
        rank,
        // RAW: Ensnare lasts rank rounds; if unspecified, default to rank.
        duration: duration ?? rank,
    }),

    burn: (id: string, target: EffectTarget, rank: number = 1, duration?: number): Effect => ({
        id,
        name: `Burn ${rank}`,
        description:
            'Applies damage over time each round per Burn rating; see weapon Burn rules.',
        target,
        behavior: { type: 'active', trigger: 'round-end' },
        type: 'status',
        status: 'burn',
        rank,
        overTimeDamage: rank,
        overTimeType: 'wounds',
        // Some sources specify duration; otherwise handle per your engine’s burn handling.
        duration,
    }),
};