import {Participant} from "@/state/participantsStore";

export type EffectTarget = {
    type: 'character' | 'initiative' | 'global';
    participantId?: string;
    slot?: number;
};

export type EffectBehavior = {
    type: 'active' | 'passive' | 'reminder';
    trigger: 'immediate' | 'turn-start' | 'turn-action' | 'turn-end' | 'round-start' | 'round-end';
};

/**
 * Effect duration:
 *   number      → fires at TURN_END decrement; auto-removed when it hits 0
 *   'encounter' → cleared on ENCOUNTER_END
 *   undefined   → indefinite (until manually removed / healed)
 */
export type EffectDuration = number | 'encounter' | undefined;

export interface ToastConfig {
    title: string;
    description?: string;
    status?: 'info' | 'warning' | 'success' | 'error';
}

export interface Effect {
    id: string;
    name: string;
    description?: string;
    target: EffectTarget;
    behavior: EffectBehavior;
    type?: string;
    duration?: EffectDuration;
    apply?: (participant?: Participant, durationMessage?: string) => void;

    // Extended fields for common SWRPG statuses (optional for backward compatibility)
    status?: StatusType;
    // Rank (X) for effects like Disoriented X, Ensnared X, Burn X
    rank?: number;
    // Damage over time (e.g., Burn, Bleeding Out)
    overTimeDamage?: number;
    overTimeType?: 'wounds' | 'strain';
}

export interface ParticipantEffect extends Effect {
    type: string;
    duration: EffectDuration;
}

export interface ActiveEffect {
    effect: ParticipantEffect;
    target: EffectTarget;
    remainingDuration: EffectDuration;
    appliedAt: number;
}

// Classification of common SWRPG status effects
export type StatusType =
    | 'staggered'
    | 'prone'
    | 'disoriented'
    | 'immobilized'
    | 'ensnared'
    | 'knocked-down'
    | 'burn'
    // Crit-derived statuses (mostly markers; some have triggers)
    | 'slowed'
    | 'distracted'
    | 'off-balance'
    | 'hamstrung'
    | 'compromised'
    | 'temporarily-lame'
    | 'head-ringer'
    | 'at-the-brink'
    | 'crippled'
    | 'maimed'
    | 'horrific-injury'
    | 'end-is-nigh'
    | 'mortally-wounded'
    | 'bleeding-out';

// Factories to create standardized status effects
// Note: id should be generated by the caller (e.g., nanoid)
export const StatusFactories = {
    staggered: (id: string, target: EffectTarget, duration: number = 1): Effect => ({
        id,
        name: 'Staggered',
        description: 'Cannot perform actions while staggered.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'staggered',
        duration,
    }),

    prone: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Prone',
        description:
            'Treated as prone: stand up with a maneuver; melee/ranged modifiers apply per rules.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'prone',
        // Duration intentionally undefined; remove when the character stands up.
    }),

    disoriented: (id: string, target: EffectTarget, rank: number = 1, duration: number = 1): Effect => ({
        id,
        name: `Disoriented ${rank}`,
        description: `Suffers ${rank} Setback on all checks while disoriented.`,
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'disoriented',
        rank,
        duration,
    }),

    immobilized: (id: string, target: EffectTarget, duration: number = 1): Effect => ({
        id,
        name: 'Immobilized',
        description: 'Cannot perform maneuvers.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'immobilized',
        duration,
    }),

    ensnared: (id: string, target: EffectTarget, rank: number = 1, duration?: number): Effect => ({
        id,
        name: `Ensnared ${rank}`,
        description:
            'Cannot perform maneuvers for X rounds (may attempt to break free per rules).',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'ensnared',
        rank,
        // RAW: Ensnare lasts rank rounds; if unspecified, default to rank.
        duration: duration ?? rank,
    }),

    burn: (id: string, target: EffectTarget, rank: number = 1, duration?: number): Effect => ({
        id,
        name: `Burn ${rank}`,
        // RAW: target suffers damage equal to the weapon's Burn rating at the
        // start of his turn for a number of rounds equal to the rank of Burn.
        description: `Suffer ${rank} wound${rank === 1 ? '' : 's'} at the start of your turn.`,
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'burn',
        rank,
        overTimeDamage: rank,
        overTimeType: 'wounds',
        // Default the on-fire duration to the Burn rank if the caller didn't specify.
        duration: duration ?? rank,
    }),

    // ── Crit-derived statuses ───────────────────────────────────────────────

    slowed: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Slowed',
        description: 'Acts in the last allied initiative slot on their next turn.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'slowed',
        duration: 1,
    }),

    distracted: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Distracted',
        description: 'Cannot perform a free maneuver during next turn.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'distracted',
        duration: 1,
    }),

    offBalance: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Off-Balance',
        description: 'Adds 1 Setback to next skill check.',
        target,
        behavior: { type: 'passive', trigger: 'immediate' },
        type: 'status',
        status: 'off-balance',
        duration: 1,
    }),

    hamstrung: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Hamstrung',
        description: 'Reduce speed by 1 until end of encounter.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'hamstrung',
        duration: 'encounter',
    }),

    compromised: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Compromised',
        description: 'Increase difficulty of all skill checks by 1 until end of encounter.',
        target,
        behavior: { type: 'passive', trigger: 'immediate' },
        type: 'status',
        status: 'compromised',
        duration: 'encounter',
    }),

    temporarilyLame: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Temporarily Lame',
        description: 'Cannot perform free maneuvers until end of encounter.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'temporarily-lame',
        duration: 'encounter',
    }),

    headRinger: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Head Ringer',
        description: 'Increase difficulty of Intellect and Cunning checks by 1 until healed.',
        target,
        behavior: { type: 'passive', trigger: 'immediate' },
        type: 'status',
        status: 'head-ringer',
        // Indefinite — until healed.
    }),

    atTheBrink: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'At the Brink',
        description: 'Suffer 1 Strain each time you perform an action.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-action' },
        type: 'status',
        status: 'at-the-brink',
    }),

    bleedingOut: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Bleeding Out',
        // RAW: target suffers 1 wound and 1 strain at the beginning of his turn each round.
        description: 'Suffer 1 wound and 1 strain at the beginning of your turn each round.',
        target,
        behavior: { type: 'active', trigger: 'turn-start' },
        type: 'status',
        status: 'bleeding-out',
        overTimeDamage: 1,
        overTimeType: 'wounds',
    }),

    maimed: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Maimed',
        description: 'Lost a limb or major appendage (cybernetic replacement required).',
        target,
        behavior: { type: 'reminder', trigger: 'immediate' },
        type: 'status',
        status: 'maimed',
    }),

    crippled: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Crippled',
        description: 'Half of damage suffered (round up) becomes Strain until healed.',
        target,
        behavior: { type: 'reminder', trigger: 'immediate' },
        type: 'status',
        status: 'crippled',
    }),

    horrificInjury: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Horrific Injury',
        description: 'One random characteristic is reduced by 1 until healed.',
        target,
        behavior: { type: 'reminder', trigger: 'immediate' },
        type: 'status',
        status: 'horrific-injury',
    }),

    endIsNigh: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'The End is Nigh',
        description: 'Make a Hard check to act each turn until healed.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'end-is-nigh',
    }),

    mortallyWounded: (id: string, target: EffectTarget): Effect => ({
        id,
        name: 'Mortally Wounded',
        description: 'Make a Daunting check at the start of each turn or die.',
        target,
        behavior: { type: 'reminder', trigger: 'turn-start' },
        type: 'status',
        status: 'mortally-wounded',
    }),
};