const skillMap = {
  "astrogation": "intelligence",
  "athletics": "brawn",
  "brawl": "brawn",
  "charm": "presence",
  "coercion": "willpower",
  "computers": "intelligence",
  "cool": "presence",
  "coordination": "agility",
  "deception": "cunning",
  "discipline": "willpower",
  "gunnery": "agility",
  "leadership": "presence",
  "mechanics": "intelligence",
  "medicine": "intelligence",
  "melee": "brawn",
  "negotiation": "presence",
  "perception": "cunning",
  "piloting: Planetary": "agility",
  "piloting: Space": "agility",
  "ranged: Light": "agility",
  "ranged: Heavy": "agility",
  "resilience": "brawn",
  "skulduggery": "cunning",
  "stealth": "agility",
  "streetwise": "cunning",
  "survival": "cunning",
  "vigilance": "willpower",
  "core worlds": "intelligence",
  "education": "intelligence",
  "lore": "intelligence",
  "outer rim": "intelligence",
  "underworld": "intelligence",
  "xenology": "intelligence",
}


export default skillMap;