"""Auto-classify the 688 unlabeled adversaries.

Reads /tmp/unlabeled.txt (one display name per line) and writes /tmp/new_labels.txt
in the same `<label>\\t<name>\\n` format used by named_character_labels.txt.

Anything in NAMED is labelled `y`; everything else is labelled `n`.
The user should spot-check the result before merging.
"""

NAMED = {
    "3D-4K, Administrative Droid",
    "Aayla Secura",
    "Adi Gallia",
    "Admiral Ackbar",
    "Admiral Tarkin (HoBS)",
    "Admiral Yularen",
    "Aimee “Flutterplume” Kraeff, Pit Fighter",
    "Am Vida",
    "Anakin Skywalker (Child)",
    "Anakin Skywalker (HoBS)",
    "Angu Drombb",
    "Arend Shen",
    "Aris Shen",
    "Bail Organa (HoBS)",
    "Bargos’s or Rebel Gamorrean",
    "Baron Administrator Lando Calrissian",
    "Barriss Offee",
    "Barriss Offee (Fallen)",
    "Barrows’ Thug",
    "BD-1",
    "Bhurra, Lutrillian Thug",
    "Biala Vale",
    "Bo-Katan Kryze",
    "Boba Fett (Child)",
    "“Boss” Trelon",
    "Brana Tsaro, Mercenary Leader",
    "Bric",
    "Brossk K’yyl",
    "Brother Viscus",
    "Burr Naxis",
    "BX-2R (“Toor”)",
    "C-21 Highsinger",
    "Captain Balrekk",
    "Captain Bialar Selis",
    "Captain Gial Ackbar (HoBS)",
    "Captain Harl Bess",
    "Captain Phasma",
    "Captain Raymus Antilles",
    "Captain Rel Harsol",
    "Captain Rex (HoBS)",
    "Captain Shorwarr",
    "Captain Talkar",
    "Cassie Cryar",
    "Cato Parasitti",
    "Chairman Papanoida",
    "Chara Tull, Corporate Co-Pilot",
    "Chell “Cold Case” Wi’eeda, Journeyman Hunter",
    "Cin Drallig",
    "Clik",
    "Cloud",
    "CN-DR, Jedi Hunter’s Droid",
    "Coleman Kcaj",
    "Colonel Meebur Gascon",
    "Commander Abyss",
    "Commander Cody",
    "Commander Danel Qurno",
    "Commander Treaska",
    "Cordal’s Chain Apprentice",
    "Cordal’s Chain Journeyman",
    "Corporal Danith Nodar",
    "Count Dooku (HoBS)",
    "Cratala",
    "Crosshair",
    "Dalan Oberos",
    "Dantris “Dani” Solomani",
    "Darth Bane (Apparition)",
    "Darth Plagueis",
    "Deil Kadru, Village Elder",
    "Dengar (HoBS)",
    "Depa Billaba",
    "Derrown",
    "Dexter Jettster",
    "Doctor Lorren Morrick",
    "Doge Nakha Urus",
    "Dokar Venas",
    "Dooku (Jedi Master)",
    "Doran’enok",
    "Dorrian Vodani, Dressellian Pilot",
    "Duchess Salandra Faust",
    "Duchess Satine Kryze",
    "Duke Erron Irbian",
    "Durge",
    "Echiella",
    "Eerig, Nightbrother Lieutenant",
    "Eeth Koth",
    "El-Les",
    "Elaiza, Jedi in Exile",
    "Ellor Orgraal, Imperial Governor",
    "Embo",
    "EV-8D3, Merendata Ev Supervisor Droid",
    "Even Piell",
    "Finis Valorum",
    "Freff, Nightbrother Leader",
    "FX-769, Medical Assistant Droid",
    "Gaav Fennro, Rebellion Intelligence Officer",
    "Gantel Dro",
    "Garulo, Hutt Cartel Gunner",
    "Gel Marcolf",
    "General Ran Niall",
    "General Tandin",
    "Gerk, Houk Supervisor",
    "Gerrol Hunn, Corporate Pilot",
    "Gome",
    "Graf Lind, Former Pirate",
    "Grax and Gremka",
    "Greedo",
    "Gruuzhnag",
    "Haril Zense, Rebel Spy",
    "Heder Brant",
    "Hondo Ohnaka (HoBS)",
    "Illo Vandin, Herglic Crime Lord",
    "Impact",
    "Irrica the Hutt",
    "ISB Agent Lorn Bal",
    "ISB Supervisor Cal Alsen",
    "Isshtharr, Wookiee Warrior",
    "IT-3PO",
    "Jango Fett",
    "Jar Jar Binks",
    "Jax Torani",
    "Jayk, Veteran Clone Trooper",
    "Jeela Scoria Harik",
    "Jerid Sykes, Consortium Admiral",
    "Jerserra (Early)",
    "Jerserra (Late)",
    "Jerserra’s Mercenary",
    "Jobel, Bothan slicer",
    "Jocasta Nu",
    "Jodo Kast",
    "Jora",
    "JR-12, Independent Security Contractor",
    "Jyd Renyr, Arena Manager",
    "K4-76A",
    "Kaina Forrel",
    "Kaltho the Hutt, Crime Lord",
    "Karg Brothers",
    "Kargrek",
    "Kassh'ka, Seasoned Hunter",
    "Kath Scarlet",
    "Kavia Slen, junk and tech dealer",
    "Kessra",
    "Ki-Adi-Mundi",
    "King Katuunko",
    "King Sanjay Rash",
    "Kit Fisto",
    "K’Kruhk",
    "Koochoo, ASP-Series Labor Droid",
    "Krash, Sorority Kill Team Leader",
    "Krezo Wasanti, Fence",
    "Kul Teska",
    "Lanni",
    "Lathe, Sorority Slicer",
    "Latts Razzi",
    "Lieutenant Aden",
    "Lieutenant Sarev",
    "Liir Wyn",
    "Lobot, Cyborg Bureaucrat",
    "“Lookout”, Exploration Droid",
    "Lor Keln",
    "Lt. Masi Qual, Bothan Spy",
    "Lt. Rik Torrence",
    "Lt. Voor, Imperial Officer",
    "Luminara Unduli",
    "Lux Bonteri",
    "M5-BZ",
    "Mace Windu",
    "Major General Billek Vilneon",
    "Major Jex Karvek – Commando Raider",
    "Major Yalor",
    "Malau Jocaos, Imperial intelligence Agent",
    "Malefax",
    "Mandi, Revah’s Bodyguard",
    "Marus Grayson, Corrupt Imperial Exchequer",
    "Marv Moray",
    "Mas Amedda",
    "Master Hunter Tor Cordol",
    "Maul (HoBS)",
    "Maya, Alderaanian Agent",
    "Micael Torval, Professional Sabacc Player",
    "Mik-Los Arnet",
    "Mil Mikkir, Chagrian Executive",
    "Mina Bonteri",
    "Misha Vontoba",
    "Moff Dardano",
    "Moff Dardano’s Bodyguard",
    "Mon Mothma (HoBS)",
    "Moralo Eval",
    "Morgan Artumar, Jedi Hunter",
    "Narralla",
    "Neero, Crime Broker",
    "Nel Henol",
    "Nik Kormir, Resistance Purchaser",
    "Noira, Pirate Queen",
    "Norta",
    "Nossor Ri",
    "Nute Gunray",
    "Nuuno",
    "Nuvo Vindi",
    "Oake, Veteran Clone Trooper",
    "Obi-Wan Kenobi (HoBS)",
    "Obi-Wan Kenobi (Padawan)",
    "Old Daka",
    "Onrein Hasa",
    "Oppo Rancisis",
    "Orphne",
    "Osi Sobeck",
    "Overseer Brynn",
    "Pathran Helshar",
    "Peekay 4 and Peekay 7",
    "Pinder Ukka",
    "Plo Koon",
    "Poggle The Lesser",
    "Pon",
    "Pong Krell",
    "Porel Vakra, Zann Consortium Underboss",
    "Pos Podura, Twi’lek associate",
    "Pravon, Gorensla Lieutenant",
    "Pre Vizsla",
    "Prime Minister Almec",
    "Prince Lee-Char",
    "Priska K’yyl",
    "Professor Huyang",
    "Puggles Trodd",
    "QT-KT",
    "Queen Breha Organa",
    "Queen Julia",
    "Queen Miraj Scintel",
    "Qui-Gon Jinn",
    "Quinlan Vos",
    "R2-B7, Astromech Droid",
    "Rafe, Veteran Clone Trooper",
    "Rako Hardeen",
    "Rav Naaran",
    "Rawwk",
    "Rear Admiral Olenka Zavalle",
    "Red-Eye Dren",
    "Reevos",
    "Reom",
    "Revah, Decoy Pirate Queen",
    "Riff Tamson",
    "Rig Nema",
    "Robonino",
    "Rolo Presat",
    "RT-3PO",
    "Rush Clovis",
    "RX-7246",
    "Ryale Wei, Majordomo",
    "Saesee Tiin",
    "Savage Opress (Natural)",
    "Saw Gerrera (HoBS)",
    "Sebulba",
    "Senator Lott Dod",
    "Senex, Krath War Droid",
    "Senior Advisor Setenna Hase",
    "Sergeant Hunter",
    "Seripas",
    "Seripas (Armoured)",
    "Shaak Ti",
    "Shen’s Goons",
    "Shmi Skywalker",
    "Shreya Ordassa, Togrutan Academic",
    "Sifo-Dyas",
    "Sinasu the Hutt",
    "Sionver Boll",
    "Sly Moore",
    "Sora Bulq",
    "Sprantal",
    "Steela Gerrera",
    "Storm",
    "Stormtrooper Captain TH-313",
    "Strike",
    "Sugi",
    "Suljo Warde",
    "Switch, 3rd Degree Protocol Droid",
    "Switch’s Thugs",
    "Sy Snootles",
    "Tabarith’s Thug",
    "Tam Blackstar",
    "Tarfful",
    "Tarryn Rayzer, Eccentric Pilot",
    "Tennom",
    "Tera Sinube",
    "Thaelo",
    "The Anvil, Arena Fighter",
    "The Carbine, Hutt Cartel Pilot",
    "The Gatekeeper",
    "Therm Scissorpunch",
    "Tholme",
    "Thweek, Kubaz Spy",
    "Tiplar",
    "Tiplee",
    "Todo 360",
    "Tojo, Veteran Clone Trooper",
    "“Too Low” Talo",
    "Tor Haido",
    "Trex, Trandoshan Slaver",
    "TT-3P0",
    "U9-C4",
    "Urel Haydon",
    "Urtuaa Haaot, Ithorian Diplomat",
    "Var Narek, Lt. Field Assistant",
    "Vazus Mandrake",
    "Venlana Sipal, Consortium Underboss",
    "Vinon Scorne",
    "Vorn Tel-Ovis",
    "Vorse Tabarith, Mob Boss",
    "Vrixx’tt",
    "Vursonk",
    "VX-19, Engineer Droid",
    "WAC-47",
    "Walisi",
    "Warg, Savrip Guard",
    "Warrick Raden",
    "Warrick’s Thugs",
    "Wat Tambor",
    "Watto",
    "Wol Kessix, Resistance Agent",
    "Wrecker",
    "Wrecker (HoBS)",
    "Yav Yiyar",
    "Yeel Dresk",
    "Yiyar Clan Members",
    "Yiyar Salvage Tech",
    "Zam Wesell",
    "Zardra",
    "Zayda",
    "Zeke, Clone Trooper Platoon Leader",
    "“Zekra Fol”, ISB Operative",
    "Zel N’got",
    "Ziro the Hutt",
}


def main():
    with open("/tmp/unlabeled.txt", "r", encoding="utf-8") as fh:
        names = [line.rstrip("\n") for line in fh if line.strip()]

    missing_from_input = NAMED - set(names)
    if missing_from_input:
        # Helpful sanity check: any names in NAMED that aren't in the input?
        # Often means a smart-quote/apostrophe mismatch.
        print(f"WARNING: {len(missing_from_input)} NAMED entries not found in /tmp/unlabeled.txt:")
        for n in sorted(missing_from_input):
            print(f"  {n!r}")

    out_lines = []
    y_count = 0
    for name in names:
        label = "y" if name in NAMED else "n"
        if label == "y":
            y_count += 1
        out_lines.append(f"{label}\t{name}\n")

    with open("/tmp/new_labels.txt", "w", encoding="utf-8") as fh:
        fh.writelines(out_lines)

    print(f"Wrote {len(out_lines)} labels to /tmp/new_labels.txt ({y_count} y, {len(out_lines)-y_count} n)")


if __name__ == "__main__":
    main()
