/**
 * userContentStore — the GM's own authored prep content (campaign-level):
 * encounters they build themselves and a "tonight's roster" of NPCs queued to
 * appear. Distinct from `sessionPrepStore` (the *active* scene, session-scoped)
 * and from the bundled `ENCOUNTER_TEMPLATES` samples. Persisted under its own
 * key so clearing session state never wipes the GM's library.
 */
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { nanoid } from 'nanoid';
import { holocronPersist } from './persist';
import type { EncounterTemplate } from '@/data/encounterTemplates';

export interface RosterEntry {
  id: string;
  name: string;
  faction?: string;
  note?: string;
  /** Spotlight adversary id — when set, the entry can be one-click dropped
   * into the live encounter as a participant. */
  adversaryId?: string;
  /** Minion group size / number of copies to add when dropped in. */
  count?: number;
  /** Optional parent squad (RosterGroup id). Absent = a loose individual. */
  groupId?: string;
  /** Optional portrait/reference image URL — shown as a row thumbnail and
   * flashable to the player view. */
  image?: string;
  /** Pinned to the always-visible "Pinned" strip at the top of the roster
   * (lifted out of its squad / loose list while pinned). */
  pinned?: boolean;
}

/** A named squad — bundles several distinct roster NPCs under one label so the
 * GM can drop a whole scene's cast in at once (e.g. "Spec-Force Unit"). The
 * roster array itself stays flat; membership is the entry's `groupId`. */
export interface RosterGroup {
  id: string;
  name: string;
  note?: string;
  /** Drop-in squad: when expanded, show a super-compact name list rather than
   * full member rows. For squads you drop wholesale into an encounter. */
  compact?: boolean;
}

interface UserContentStore {
  userEncounters: EncounterTemplate[];
  roster: RosterEntry[];
  rosterGroups: RosterGroup[];

  /** Upsert an encounter by id (create if new, replace if it exists). */
  saveEncounter: (encounter: EncounterTemplate) => void;
  /** Patch fields of an existing encounter — used by inline editing. */
  updateEncounter: (id: string, patch: Partial<EncounterTemplate>) => void;
  /** Clone a scene (fresh ids, "(copy)" title) inserted right after the source. */
  duplicateEncounter: (id: string) => void;
  removeEncounter: (id: string) => void;

  addRosterEntry: (entry: Omit<RosterEntry, 'id'>) => void;
  updateRosterEntry: (id: string, patch: Partial<RosterEntry>) => void;
  removeRosterEntry: (id: string) => void;

  addRosterGroup: (group: RosterGroup) => void;
  updateRosterGroup: (id: string, patch: Partial<RosterGroup>) => void;
  /** Removes the squad but keeps its NPCs — they fall back to loose entries. */
  removeRosterGroup: (id: string) => void;
}

/** Prefix marks an encounter as GM-authored so it never collides with a
 * bundled sample id and the panel can tell the two apart. */
export function newEncounterId(): string {
  return `user-${nanoid(8)}`;
}

/** Id for a new squad. Generated by the caller so it can immediately move an
 * entry into the freshly-created group. */
export function newRosterGroupId(): string {
  return `group-${nanoid(8)}`;
}

const useUserContentStore = create<UserContentStore>()(persist((set) => ({
  userEncounters: [],
  roster: [],
  rosterGroups: [],

  saveEncounter: (encounter) =>
    set((state) => {
      const exists = state.userEncounters.some((e) => e.id === encounter.id);
      return {
        userEncounters: exists
          ? state.userEncounters.map((e) => (e.id === encounter.id ? encounter : e))
          : [...state.userEncounters, encounter],
      };
    }),
  updateEncounter: (id, patch) =>
    set((state) => ({
      userEncounters: state.userEncounters.map((e) => (e.id === id ? { ...e, ...patch } : e)),
    })),
  duplicateEncounter: (id) =>
    set((state) => {
      const idx = state.userEncounters.findIndex((e) => e.id === id);
      if (idx === -1) return state;
      const src = state.userEncounters[idx];
      // Fresh table/row ids so the clone's keys never collide with the source.
      const copy: EncounterTemplate = {
        ...src,
        id: newEncounterId(),
        title: src.title ? `${src.title} (copy)` : '',
        tags: src.tags ? [...src.tags] : undefined,
        beats: src.beats ? [...src.beats] : undefined,
        npcs: src.npcs?.map((n) => (typeof n === 'string' ? n : { ...n })),
        tables: src.tables?.map((t) => ({
          ...t,
          id: nanoid(6),
          rows: t.rows.map((r) => ({ ...r, id: nanoid(6) })),
        })),
      };
      const next = [...state.userEncounters];
      next.splice(idx + 1, 0, copy);
      return { userEncounters: next };
    }),
  removeEncounter: (id) =>
    set((state) => ({
      userEncounters: state.userEncounters.filter((e) => e.id !== id),
    })),

  addRosterEntry: (entry) =>
    set((state) => ({ roster: [...state.roster, { ...entry, id: nanoid(8) }] })),
  updateRosterEntry: (id, patch) =>
    set((state) => ({
      roster: state.roster.map((r) => (r.id === id ? { ...r, ...patch } : r)),
    })),
  removeRosterEntry: (id) =>
    set((state) => ({ roster: state.roster.filter((r) => r.id !== id) })),

  addRosterGroup: (group) =>
    set((state) => ({ rosterGroups: [...state.rosterGroups, group] })),
  updateRosterGroup: (id, patch) =>
    set((state) => ({
      rosterGroups: state.rosterGroups.map((g) => (g.id === id ? { ...g, ...patch } : g)),
    })),
  removeRosterGroup: (id) =>
    set((state) => ({
      rosterGroups: state.rosterGroups.filter((g) => g.id !== id),
      // Keep the NPCs — they just become loose individuals again.
      roster: state.roster.map((r) => (r.groupId === id ? { ...r, groupId: undefined } : r)),
    })),
}), holocronPersist({
  name: 'userContent',
  partialize: (s) => ({
    userEncounters: s.userEncounters,
    roster: s.roster,
    rosterGroups: s.rosterGroups,
  }),
})));

export default useUserContentStore;
